In [105]:
import pandas_datareader.data as reader
import pandas as pd
import numpy as np
import datetime as dt
import statsmodels.api as sm
import datetime
import yfinance as yf
import matplotlib.pyplot as plt

In [6]:
start = (datetime.datetime(2018, 1, 1))
end = (datetime.datetime(2020, 1, 1))

In [10]:
symbol = ['ADBE']

In [12]:
start = (datetime.datetime(2018, 1, 1))
end = (datetime.datetime(2020, 1, 1))

data = yf.download(symbol, start=start, end=end)
data.rename(columns={"Close": 'close', "High": 'high', "Low": 'low', 'Volume': 'volume', 'Open': 'open'}, inplace=True)
print(data.head())

[*********************100%***********************]  1 of 1 completed
                  open        high         low       close   Adj Close  \
Date                                                                     
2018-01-02  175.850006  177.800003  175.259995  177.699997  177.699997   
2018-01-03  178.000000  181.889999  177.699997  181.039993  181.039993   
2018-01-04  181.929993  184.059998  181.639999  183.220001  183.220001   
2018-01-05  185.000000  185.899994  183.539993  185.339996  185.339996   
2018-01-08  184.949997  185.600006  183.830002  185.039993  185.039993   

             volume  
Date                 
2018-01-02  2432800  
2018-01-03  2561200  
2018-01-04  2211400  
2018-01-05  2376500  
2018-01-08  2088000  


In [13]:
data = data[["Adj Close"]]

In [14]:
data

Adj Close
Date                  
2018-01-02  177.699997
2018-01-03  181.039993
2018-01-04  183.220001
2018-01-05  185.339996
2018-01-08  185.039993
...                ...
2019-12-24  329.640015
2019-12-26  331.200012
2019-12-27  330.790009
2019-12-30  328.339996
2019-12-31  329.809998

[503 rows x 1 columns]

In [24]:
Y = np.diff(np.log(data['Adj Close']))

In [26]:
type(Y)

numpy.ndarray

In [28]:
df = pd.DataFrame(Y, columns = ['Adj Close'])

In [29]:
df

Adj Close
0     0.018621
1     0.011970
2     0.011504
3    -0.001620
4     0.008931
..         ...
497   0.002095
498   0.004721
499  -0.001239
500  -0.007434
501   0.004467

[502 rows x 1 columns]

In [107]:
factors = pd.read_csv("fama-french.csv", skiprows=3 )

In [33]:
factors

Unnamed: 0  Mkt-RF   SMB   HML   RMW   CMA     RF
0        19630701   -0.67  0.00 -0.34 -0.01  0.15  0.012
1        19630702    0.79 -0.27  0.27 -0.07 -0.19  0.012
2        19630703    0.63 -0.17 -0.10  0.17 -0.33  0.012
3        19630705    0.40  0.08 -0.27  0.08 -0.33  0.012
4        19630708   -0.63  0.04 -0.19 -0.29  0.13  0.012
...           ...     ...   ...   ...   ...   ...    ...
14509    20210222   -1.12  0.68  3.14  1.66  0.90  0.000
14510    20210223   -0.15 -1.05  0.90  1.08 -0.19  0.000
14511    20210224    1.15  1.48  1.34 -0.29  0.32  0.000
14512    20210225   -2.73 -0.90  0.87  1.00  0.47  0.000
14513    20210226   -0.28  0.38 -1.56 -0.06 -0.38  0.000

[14514 rows x 7 columns]

In [41]:
factors.rename({"Unnamed: 0" : "Date"}, inplace=True,axis='columns')

In [43]:
factors.index = factors.Date

In [47]:
factors

Date  Mkt-RF   SMB   HML   RMW   CMA     RF
Date                                                     
19630701  19630701   -0.67  0.00 -0.34 -0.01  0.15  0.012
19630702  19630702    0.79 -0.27  0.27 -0.07 -0.19  0.012
19630703  19630703    0.63 -0.17 -0.10  0.17 -0.33  0.012
19630705  19630705    0.40  0.08 -0.27  0.08 -0.33  0.012
19630708  19630708   -0.63  0.04 -0.19 -0.29  0.13  0.012
...            ...     ...   ...   ...   ...   ...    ...
20210222  20210222   -1.12  0.68  3.14  1.66  0.90  0.000
20210223  20210223   -0.15 -1.05  0.90  1.08 -0.19  0.000
20210224  20210224    1.15  1.48  1.34 -0.29  0.32  0.000
20210225  20210225   -2.73 -0.90  0.87  1.00  0.47  0.000
20210226  20210226   -0.28  0.38 -1.56 -0.06 -0.38  0.000

[14514 rows x 7 columns]

In [51]:
factors.dtypes

Date        int64
Mkt-RF    float64
SMB       float64
HML       float64
RMW       float64
CMA       float64
RF        float64
dtype: object

In [53]:
factors['Date'] = pd.to_datetime(factors['Date'], format='%Y%m%d')

In [54]:
factors

Date  Mkt-RF   SMB   HML   RMW   CMA     RF
Date                                                      
19630701 1963-07-01   -0.67  0.00 -0.34 -0.01  0.15  0.012
19630702 1963-07-02    0.79 -0.27  0.27 -0.07 -0.19  0.012
19630703 1963-07-03    0.63 -0.17 -0.10  0.17 -0.33  0.012
19630705 1963-07-05    0.40  0.08 -0.27  0.08 -0.33  0.012
19630708 1963-07-08   -0.63  0.04 -0.19 -0.29  0.13  0.012
...             ...     ...   ...   ...   ...   ...    ...
20210222 2021-02-22   -1.12  0.68  3.14  1.66  0.90  0.000
20210223 2021-02-23   -0.15 -1.05  0.90  1.08 -0.19  0.000
20210224 2021-02-24    1.15  1.48  1.34 -0.29  0.32  0.000
20210225 2021-02-25   -2.73 -0.90  0.87  1.00  0.47  0.000
20210226 2021-02-26   -0.28  0.38 -1.56 -0.06 -0.38  0.000

[14514 rows x 7 columns]

In [56]:
start

datetime.datetime(2018, 1, 1, 0, 0)

In [87]:
fama = factors[(factors["Date"] > start) & (factors["Date"] <= '2020-01-01')]

In [92]:
fama = fama.iloc[1:,:]

In [95]:
fama

Date  Mkt-RF   SMB   HML   RMW   CMA     RF
Date                                                      
20180103 2018-01-03    0.59 -0.48 -0.20 -0.74 -0.07  0.005
20180104 2018-01-04    0.42 -0.23  0.25 -0.02  0.30  0.005
20180105 2018-01-05    0.66 -0.36 -0.26  0.39 -0.37  0.005
20180108 2018-01-08    0.19 -0.21  0.05 -0.09  0.03  0.005
20180109 2018-01-09    0.15 -0.36 -0.05 -0.11 -0.06  0.005
...             ...     ...   ...   ...   ...   ...    ...
20191224 2019-12-24    0.01  0.36 -0.02 -0.28  0.03  0.007
20191226 2019-12-26    0.48 -0.56 -0.02  0.22 -0.20  0.007
20191227 2019-12-27   -0.10 -0.54 -0.07  0.25  0.15  0.007
20191230 2019-12-30   -0.57  0.27  0.59  0.13  0.45  0.007
20191231 2019-12-31    0.28  0.02  0.11 -0.11  0.20  0.007

[502 rows x 7 columns]

In [98]:
fama.reset_index(drop=True, inplace=True)

In [102]:
adbe = fama.join(df, how='outer')

In [103]:
adbe

Date  Mkt-RF   SMB   HML   RMW   CMA     RF  Adj Close
0   2018-01-03    0.59 -0.48 -0.20 -0.74 -0.07  0.005   0.018621
1   2018-01-04    0.42 -0.23  0.25 -0.02  0.30  0.005   0.011970
2   2018-01-05    0.66 -0.36 -0.26  0.39 -0.37  0.005   0.011504
3   2018-01-08    0.19 -0.21  0.05 -0.09  0.03  0.005  -0.001620
4   2018-01-09    0.15 -0.36 -0.05 -0.11 -0.06  0.005   0.008931
..         ...     ...   ...   ...   ...   ...    ...        ...
497 2019-12-24    0.01  0.36 -0.02 -0.28  0.03  0.007   0.002095
498 2019-12-26    0.48 -0.56 -0.02  0.22 -0.20  0.007   0.004721
499 2019-12-27   -0.10 -0.54 -0.07  0.25  0.15  0.007  -0.001239
500 2019-12-30   -0.57  0.27  0.59  0.13  0.45  0.007  -0.007434
501 2019-12-31    0.28  0.02  0.11 -0.11  0.20  0.007   0.004467

[502 rows x 8 columns]

In [111]:
corr = adbe.corr()
corr.style.background_gradient(cmap='BrBG').set_precision(2)
# 'RdBu_r' & 'BrBG' are other good diverging colormaps

## OLS

In [118]:
import numpy as np
import scipy.stats as ss
import pandas as pd

In [119]:
adbe

Date  Mkt-RF   SMB   HML   RMW   CMA     RF  Adj Close
0   2018-01-03    0.59 -0.48 -0.20 -0.74 -0.07  0.005   0.018621
1   2018-01-04    0.42 -0.23  0.25 -0.02  0.30  0.005   0.011970
2   2018-01-05    0.66 -0.36 -0.26  0.39 -0.37  0.005   0.011504
3   2018-01-08    0.19 -0.21  0.05 -0.09  0.03  0.005  -0.001620
4   2018-01-09    0.15 -0.36 -0.05 -0.11 -0.06  0.005   0.008931
..         ...     ...   ...   ...   ...   ...    ...        ...
497 2019-12-24    0.01  0.36 -0.02 -0.28  0.03  0.007   0.002095
498 2019-12-26    0.48 -0.56 -0.02  0.22 -0.20  0.007   0.004721
499 2019-12-27   -0.10 -0.54 -0.07  0.25  0.15  0.007  -0.001239
500 2019-12-30   -0.57  0.27  0.59  0.13  0.45  0.007  -0.007434
501 2019-12-31    0.28  0.02  0.11 -0.11  0.20  0.007   0.004467

[502 rows x 8 columns]

In [120]:
adbe.columns

Index(['Date', 'Mkt-RF', 'SMB', 'HML', 'RMW', 'CMA', 'RF', 'Adj Close'], dtype='object')

In [121]:
a_imp_features = adbe[['Mkt-RF', 'SMB', 'HML', 'RMW', 'CMA']]

In [122]:
Y = adbe["Adj Close"]

In [123]:
Y = Y
T = Y.shape[0];
# SPY = DataReader('SPY',  'yahoo', datetime(2020,1,1), datetime(2020,8,31))
# F = np.diff(np.log(SPY['Adj Close'].values))
F = a_imp_features.values
'Add Constant to X'
X = np.column_stack([np.ones((T,1)), F])
N = X.shape[1]

'REGRESSION STARTS:'       
'Linear Regression of Y: T x 1 on' 
'Regressors X: T x N'

invXX = np.linalg.inv(X.transpose()@X)
'OLS estimator beta: N x 1'
beta_hat = invXX@X.transpose()@Y
'Predictive value of Y_t using OLS'  
y_hat = X@beta_hat;       
'Residuals from OLS: Y - X*beta'        
residuals = Y - y_hat;            
'variance of Y_t or residuals'
sigma2 = (1/T)*(residuals.transpose()@residuals)
'standard deviation of Y_t or residuals'
sig = np.sqrt(sigma2) 
'variance-covariance matrix of beta_hat'
'N x N: on-diagnal variance(beta_j)'
'N x N: off-diagnal cov(beta_i, beta_j)'
varcov_beta_hat = (sigma2)*invXX
var_beta_hat = np.sqrt(T*np.diag(varcov_beta_hat))

'Calculate R-square'
R_square = 1 - residuals.transpose()@residuals/(T*np.var(Y))
adj_R_square = 1-(1-R_square)*(T-1)/(T-N)

'Test Each Coefficient: beta_i'
't-test stat: N x 1'
t_stat = beta_hat.transpose()/var_beta_hat
' t-test significance level: N x 1'
p_val_t = 1-ss.norm.cdf(t_stat)

'Test of Joint Significance of Model'
F_stat = beta_hat.transpose()@varcov_beta_hat@beta_hat/\
         (residuals.transpose()@residuals)
'size: (1 x N)*(N x N)*(N x 1)/((1 x T) * (T x 1)) = 1 x 1'

p_val_F = 1-ss.chi2.cdf(F_stat,T-N)

REPORT = np.column_stack([beta_hat, t_stat,p_val_t])
print('Regression Statistics')
print('------------------------\n')
print(' REGRESSION STATISTICS  \n') 
print('------------------------\n')
print('beta             t_stat            p_val\n')
print(REPORT)
print('\n Joint significance of all coefficients\n',[F_stat,p_val_F])
print('R-Square is       \n',R_square)
print('Adjusted R Square \n',adj_R_square)
print('Standard Error    \n',sig)
print('Observations      \n',T) 
print('-------------------------\n')

Regression Statistics
------------------------

 REGRESSION STATISTICS  

------------------------

beta             t_stat            p_val

[[ 4.07455309e-04  3.95752888e-02  4.84215864e-01]
 [ 1.18967184e-02  9.98278592e-01  1.59072143e-01]
 [-1.69860061e-03 -8.28684610e-02  5.33021934e-01]
 [-7.82942693e-03 -3.53257754e-01  6.38052393e-01]
 [-3.15059772e-03 -1.04012119e-01  5.41420134e-01]
 [-1.06938817e-02 -2.63096933e-01  6.03762066e-01]]

 Joint significance of all coefficients
 [4.258963865272715e-09, 1.0]
R-Square is       
 0.7084191013877439
Adjusted R Square 
 0.7054797778130235
Standard Error    
 0.010254720039623981
Observations      
 502
-------------------------



### Forward Selection

In [124]:
def forward_selection(data, target, significance_level=0.05):
    initial_features = data.columns.tolist()
    best_features = []
    while (len(initial_features)>0):
        remaining_features = list(set(initial_features)-set(best_features))
        new_pval = pd.Series(index=remaining_features)
        for new_column in remaining_features:
            model = sm.OLS(target, sm.add_constant(data[best_features+[new_column]])).fit()
            new_pval[new_column] = model.pvalues[new_column]
        min_p_value = new_pval.min()
        if(min_p_value<significance_level):
            best_features.append(new_pval.idxmin())
        else:
            break
    return best_features

In [125]:
X = a_imp_features

In [126]:
forward_selection(X,Y)

C:\Users\adhar\anaconda3\envs\fintech\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  
C:\Users\adhar\anaconda3\envs\fintech\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  
C:\Users\adhar\anaconda3\envs\fintech\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  
C:\Users\adhar\anaconda3\envs\fintech\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


['Mkt-RF', 'HML', 'CMA', 'RMW']

### Backward Selection

In [127]:
def backward_elimination(data, target,significance_level = 0.05):
    features = data.columns.tolist()
    while(len(features)>0):
        features_with_constant = sm.add_constant(data[features])
        p_values = sm.OLS(target, features_with_constant).fit().pvalues[1:]
        max_p_value = p_values.max()
        if(max_p_value >= significance_level):
            excluded_feature = p_values.idxmax()
            features.remove(excluded_feature)
        else:
            break 
    return features

In [128]:
backward_elimination(X,Y)

['Mkt-RF', 'HML', 'RMW', 'CMA']

### Mixed Selection

In [129]:
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.linear_model import LinearRegression

In [134]:
sffs = SFS(LinearRegression(),
         k_features=(2,4),
         forward=True,
         floating=True,
         cv=5)
sffs.fit(X, Y)
sffs.k_feature_names_

('Mkt-RF', 'HML', 'RMW', 'CMA')