In [1]:
import pandas_datareader.data as reader
import pandas as pd
import numpy as np
import datetime as dt
import statsmodels.api as sm
import datetime
import yfinance as yf
import matplotlib.pyplot as plt

In [2]:
start = (datetime.datetime(2018, 1, 1))
end = (datetime.datetime(2020, 1, 1))

In [3]:
symbol = ['ADBE']

In [4]:
start = (datetime.datetime(2018, 1, 1))
end = (datetime.datetime(2020, 1, 1))

data = yf.download(symbol, start=start, end=end)
data.rename(columns={"Close": 'close', "High": 'high', "Low": 'low', 'Volume': 'volume', 'Open': 'open'}, inplace=True)
print(data.head())

[*********************100%***********************]  1 of 1 completed
                  open        high         low       close   Adj Close  \
Date                                                                     
2018-01-02  175.850006  177.800003  175.259995  177.699997  177.699997   
2018-01-03  178.000000  181.889999  177.699997  181.039993  181.039993   
2018-01-04  181.929993  184.059998  181.639999  183.220001  183.220001   
2018-01-05  185.000000  185.899994  183.539993  185.339996  185.339996   
2018-01-08  184.949997  185.600006  183.830002  185.039993  185.039993   

             volume  
Date                 
2018-01-02  2432800  
2018-01-03  2561200  
2018-01-04  2211400  
2018-01-05  2376500  
2018-01-08  2088000  


In [5]:
data = data[["Adj Close"]]

In [6]:
data

Adj Close
Date                  
2018-01-02  177.699997
2018-01-03  181.039993
2018-01-04  183.220001
2018-01-05  185.339996
2018-01-08  185.039993
...                ...
2019-12-24  329.640015
2019-12-26  331.200012
2019-12-27  330.790009
2019-12-30  328.339996
2019-12-31  329.809998

[503 rows x 1 columns]

In [7]:
Y = np.diff(np.log(data['Adj Close']))

In [8]:
type(Y)

numpy.ndarray

In [9]:
df = pd.DataFrame(Y, columns = ['Adj Close'])

In [10]:
df

Adj Close
0     0.018621
1     0.011970
2     0.011504
3    -0.001620
4     0.008931
..         ...
497   0.002095
498   0.004721
499  -0.001239
500  -0.007434
501   0.004467

[502 rows x 1 columns]

In [11]:
factors = pd.read_csv("fama-french.csv", skiprows=3 )

In [12]:
factors

Unnamed: 0  Mkt-RF   SMB   HML   RMW   CMA     RF
0        19630701   -0.67  0.00 -0.34 -0.01  0.15  0.012
1        19630702    0.79 -0.27  0.27 -0.07 -0.19  0.012
2        19630703    0.63 -0.17 -0.10  0.17 -0.33  0.012
3        19630705    0.40  0.08 -0.27  0.08 -0.33  0.012
4        19630708   -0.63  0.04 -0.19 -0.29  0.13  0.012
...           ...     ...   ...   ...   ...   ...    ...
14509    20210222   -1.12  0.68  3.14  1.66  0.90  0.000
14510    20210223   -0.15 -1.05  0.90  1.08 -0.19  0.000
14511    20210224    1.15  1.48  1.34 -0.29  0.32  0.000
14512    20210225   -2.73 -0.90  0.87  1.00  0.47  0.000
14513    20210226   -0.28  0.38 -1.56 -0.06 -0.38  0.000

[14514 rows x 7 columns]

In [13]:
factors.rename({"Unnamed: 0" : "Date"}, inplace=True,axis='columns')

In [14]:
factors.index = factors.Date

In [15]:
factors

Date  Mkt-RF   SMB   HML   RMW   CMA     RF
Date                                                     
19630701  19630701   -0.67  0.00 -0.34 -0.01  0.15  0.012
19630702  19630702    0.79 -0.27  0.27 -0.07 -0.19  0.012
19630703  19630703    0.63 -0.17 -0.10  0.17 -0.33  0.012
19630705  19630705    0.40  0.08 -0.27  0.08 -0.33  0.012
19630708  19630708   -0.63  0.04 -0.19 -0.29  0.13  0.012
...            ...     ...   ...   ...   ...   ...    ...
20210222  20210222   -1.12  0.68  3.14  1.66  0.90  0.000
20210223  20210223   -0.15 -1.05  0.90  1.08 -0.19  0.000
20210224  20210224    1.15  1.48  1.34 -0.29  0.32  0.000
20210225  20210225   -2.73 -0.90  0.87  1.00  0.47  0.000
20210226  20210226   -0.28  0.38 -1.56 -0.06 -0.38  0.000

[14514 rows x 7 columns]

In [16]:
factors.dtypes

Date        int64
Mkt-RF    float64
SMB       float64
HML       float64
RMW       float64
CMA       float64
RF        float64
dtype: object

In [17]:
factors['Date'] = pd.to_datetime(factors['Date'], format='%Y%m%d')

In [18]:
factors

Date  Mkt-RF   SMB   HML   RMW   CMA     RF
Date                                                      
19630701 1963-07-01   -0.67  0.00 -0.34 -0.01  0.15  0.012
19630702 1963-07-02    0.79 -0.27  0.27 -0.07 -0.19  0.012
19630703 1963-07-03    0.63 -0.17 -0.10  0.17 -0.33  0.012
19630705 1963-07-05    0.40  0.08 -0.27  0.08 -0.33  0.012
19630708 1963-07-08   -0.63  0.04 -0.19 -0.29  0.13  0.012
...             ...     ...   ...   ...   ...   ...    ...
20210222 2021-02-22   -1.12  0.68  3.14  1.66  0.90  0.000
20210223 2021-02-23   -0.15 -1.05  0.90  1.08 -0.19  0.000
20210224 2021-02-24    1.15  1.48  1.34 -0.29  0.32  0.000
20210225 2021-02-25   -2.73 -0.90  0.87  1.00  0.47  0.000
20210226 2021-02-26   -0.28  0.38 -1.56 -0.06 -0.38  0.000

[14514 rows x 7 columns]

In [19]:
start

datetime.datetime(2018, 1, 1, 0, 0)

In [20]:
fama = factors[(factors["Date"] > start) & (factors["Date"] <= '2020-01-01')]

In [21]:
fama = fama.iloc[1:,:]

In [22]:
fama

Date  Mkt-RF   SMB   HML   RMW   CMA     RF
Date                                                      
20180103 2018-01-03    0.59 -0.48 -0.20 -0.74 -0.07  0.005
20180104 2018-01-04    0.42 -0.23  0.25 -0.02  0.30  0.005
20180105 2018-01-05    0.66 -0.36 -0.26  0.39 -0.37  0.005
20180108 2018-01-08    0.19 -0.21  0.05 -0.09  0.03  0.005
20180109 2018-01-09    0.15 -0.36 -0.05 -0.11 -0.06  0.005
...             ...     ...   ...   ...   ...   ...    ...
20191224 2019-12-24    0.01  0.36 -0.02 -0.28  0.03  0.007
20191226 2019-12-26    0.48 -0.56 -0.02  0.22 -0.20  0.007
20191227 2019-12-27   -0.10 -0.54 -0.07  0.25  0.15  0.007
20191230 2019-12-30   -0.57  0.27  0.59  0.13  0.45  0.007
20191231 2019-12-31    0.28  0.02  0.11 -0.11  0.20  0.007

[502 rows x 7 columns]

In [23]:
fama.reset_index(drop=True, inplace=True)

In [24]:
adbe = fama.join(df, how='outer')

In [25]:
adbe

Date  Mkt-RF   SMB   HML   RMW   CMA     RF  Adj Close
0   2018-01-03    0.59 -0.48 -0.20 -0.74 -0.07  0.005   0.018621
1   2018-01-04    0.42 -0.23  0.25 -0.02  0.30  0.005   0.011970
2   2018-01-05    0.66 -0.36 -0.26  0.39 -0.37  0.005   0.011504
3   2018-01-08    0.19 -0.21  0.05 -0.09  0.03  0.005  -0.001620
4   2018-01-09    0.15 -0.36 -0.05 -0.11 -0.06  0.005   0.008931
..         ...     ...   ...   ...   ...   ...    ...        ...
497 2019-12-24    0.01  0.36 -0.02 -0.28  0.03  0.007   0.002095
498 2019-12-26    0.48 -0.56 -0.02  0.22 -0.20  0.007   0.004721
499 2019-12-27   -0.10 -0.54 -0.07  0.25  0.15  0.007  -0.001239
500 2019-12-30   -0.57  0.27  0.59  0.13  0.45  0.007  -0.007434
501 2019-12-31    0.28  0.02  0.11 -0.11  0.20  0.007   0.004467

[502 rows x 8 columns]

In [26]:
corr = adbe.corr()
corr.style.background_gradient(cmap='BrBG').set_precision(2)
# 'RdBu_r' & 'BrBG' are other good diverging colormaps

## OLS

In [27]:
import numpy as np
import scipy.stats as ss
import pandas as pd

In [28]:
adbe

Date  Mkt-RF   SMB   HML   RMW   CMA     RF  Adj Close
0   2018-01-03    0.59 -0.48 -0.20 -0.74 -0.07  0.005   0.018621
1   2018-01-04    0.42 -0.23  0.25 -0.02  0.30  0.005   0.011970
2   2018-01-05    0.66 -0.36 -0.26  0.39 -0.37  0.005   0.011504
3   2018-01-08    0.19 -0.21  0.05 -0.09  0.03  0.005  -0.001620
4   2018-01-09    0.15 -0.36 -0.05 -0.11 -0.06  0.005   0.008931
..         ...     ...   ...   ...   ...   ...    ...        ...
497 2019-12-24    0.01  0.36 -0.02 -0.28  0.03  0.007   0.002095
498 2019-12-26    0.48 -0.56 -0.02  0.22 -0.20  0.007   0.004721
499 2019-12-27   -0.10 -0.54 -0.07  0.25  0.15  0.007  -0.001239
500 2019-12-30   -0.57  0.27  0.59  0.13  0.45  0.007  -0.007434
501 2019-12-31    0.28  0.02  0.11 -0.11  0.20  0.007   0.004467

[502 rows x 8 columns]

In [29]:
adbe.columns

Index(['Date', 'Mkt-RF', 'SMB', 'HML', 'RMW', 'CMA', 'RF', 'Adj Close'], dtype='object')

In [86]:
a_imp_features = adbe[['Mkt-RF', 'SMB', 'HML', 'RMW', 'CMA']]

In [31]:
Y = adbe["Adj Close"]

In [32]:
Y = Y
T = Y.shape[0];
# SPY = DataReader('SPY',  'yahoo', datetime(2020,1,1), datetime(2020,8,31))
# F = np.diff(np.log(SPY['Adj Close'].values))
F = a_imp_features.values
'Add Constant to X'
X = np.column_stack([np.ones((T,1)), F])
N = X.shape[1]

'REGRESSION STARTS:'       
'Linear Regression of Y: T x 1 on' 
'Regressors X: T x N'

invXX = np.linalg.inv(X.transpose()@X)
'OLS estimator beta: N x 1'
beta_hat = invXX@X.transpose()@Y
'Predictive value of Y_t using OLS'  
y_hat = X@beta_hat;       
'Residuals from OLS: Y - X*beta'        
residuals = Y - y_hat;            
'variance of Y_t or residuals'
sigma2 = (1/T)*(residuals.transpose()@residuals)
'standard deviation of Y_t or residuals'
sig = np.sqrt(sigma2) 
'variance-covariance matrix of beta_hat'
'N x N: on-diagnal variance(beta_j)'
'N x N: off-diagnal cov(beta_i, beta_j)'
varcov_beta_hat = (sigma2)*invXX
var_beta_hat = np.sqrt(T*np.diag(varcov_beta_hat))

'Calculate R-square'
R_square = 1 - residuals.transpose()@residuals/(T*np.var(Y))
adj_R_square = 1-(1-R_square)*(T-1)/(T-N)

'Test Each Coefficient: beta_i'
't-test stat: N x 1'
t_stat = beta_hat.transpose()/var_beta_hat
' t-test significance level: N x 1'
p_val_t = 1-ss.norm.cdf(t_stat)

'Test of Joint Significance of Model'
F_stat = beta_hat.transpose()@varcov_beta_hat@beta_hat/\
         (residuals.transpose()@residuals)
'size: (1 x N)*(N x N)*(N x 1)/((1 x T) * (T x 1)) = 1 x 1'

p_val_F = 1-ss.chi2.cdf(F_stat,T-N)

REPORT = np.column_stack([beta_hat, t_stat,p_val_t])
print('Regression Statistics')
print('------------------------\n')
print(' REGRESSION STATISTICS  \n') 
print('------------------------\n')
print('beta             t_stat            p_val\n')
print(REPORT)
print('\n Joint significance of all coefficients\n',[F_stat,p_val_F])
print('R-Square is       \n',R_square)
print('Adjusted R Square \n',adj_R_square)
print('Standard Error    \n',sig)
print('Observations      \n',T) 
print('-------------------------\n')

Regression Statistics
------------------------

 REGRESSION STATISTICS  

------------------------

beta             t_stat            p_val

[[ 4.07455309e-04  3.95752888e-02  4.84215864e-01]
 [ 1.18967184e-02  9.98278592e-01  1.59072143e-01]
 [-1.69860061e-03 -8.28684610e-02  5.33021934e-01]
 [-7.82942693e-03 -3.53257754e-01  6.38052393e-01]
 [-3.15059772e-03 -1.04012119e-01  5.41420134e-01]
 [-1.06938817e-02 -2.63096933e-01  6.03762066e-01]]

 Joint significance of all coefficients
 [4.258963865272715e-09, 1.0]
R-Square is       
 0.7084191013877439
Adjusted R Square 
 0.7054797778130235
Standard Error    
 0.010254720039623981
Observations      
 502
-------------------------



### Forward Selection

In [33]:
def forward_selection(data, target, significance_level=0.05):
    initial_features = data.columns.tolist()
    best_features = []
    while (len(initial_features)>0):
        remaining_features = list(set(initial_features)-set(best_features))
        new_pval = pd.Series(index=remaining_features)
        for new_column in remaining_features:
            model = sm.OLS(target, sm.add_constant(data[best_features+[new_column]])).fit()
            new_pval[new_column] = model.pvalues[new_column]
        min_p_value = new_pval.min()
        if(min_p_value<significance_level):
            best_features.append(new_pval.idxmin())
        else:
            break
    return best_features

In [34]:
X = a_imp_features

In [35]:
forward_selection(X,Y)

C:\Users\adhar\anaconda3\envs\fintech\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  
C:\Users\adhar\anaconda3\envs\fintech\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  
C:\Users\adhar\anaconda3\envs\fintech\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  
C:\Users\adhar\anaconda3\envs\fintech\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


['Mkt-RF', 'HML', 'CMA', 'RMW']

### Backward Selection

In [36]:
def backward_elimination(data, target,significance_level = 0.05):
    features = data.columns.tolist()
    while(len(features)>0):
        features_with_constant = sm.add_constant(data[features])
        p_values = sm.OLS(target, features_with_constant).fit().pvalues[1:]
        max_p_value = p_values.max()
        if(max_p_value >= significance_level):
            excluded_feature = p_values.idxmax()
            features.remove(excluded_feature)
        else:
            break 
    return features

In [37]:
backward_elimination(X,Y)

['Mkt-RF', 'HML', 'RMW', 'CMA']

### Mixed Selection

In [38]:
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.linear_model import LinearRegression

In [39]:
sffs = SFS(LinearRegression(),
         k_features=(2,4),
         forward=True,
         floating=True,
         cv=5)
sffs.fit(X, Y)
sffs.k_feature_names_

('Mkt-RF', 'HML', 'RMW', 'CMA')

In [40]:
a_imp_features = adbe[['Mkt-RF', 'HML', 'RMW', 'CMA']]

In [41]:
Y = Y
T = Y.shape[0];
# SPY = DataReader('SPY',  'yahoo', datetime(2020,1,1), datetime(2020,8,31))
# F = np.diff(np.log(SPY['Adj Close'].values))
F = a_imp_features.values
'Add Constant to X'
X = np.column_stack([np.ones((T,1)), F])
N = X.shape[1]

'REGRESSION STARTS:'       
'Linear Regression of Y: T x 1 on' 
'Regressors X: T x N'

invXX = np.linalg.inv(X.transpose()@X)
'OLS estimator beta: N x 1'
beta_hat = invXX@X.transpose()@Y
'Predictive value of Y_t using OLS'  
y_hat = X@beta_hat;       
'Residuals from OLS: Y - X*beta'        
residuals = Y - y_hat;            
'variance of Y_t or residuals'
sigma2 = (1/T)*(residuals.transpose()@residuals)
'standard deviation of Y_t or residuals'
sig = np.sqrt(sigma2) 
'variance-covariance matrix of beta_hat'
'N x N: on-diagnal variance(beta_j)'
'N x N: off-diagnal cov(beta_i, beta_j)'
varcov_beta_hat = (sigma2)*invXX
var_beta_hat = np.sqrt(T*np.diag(varcov_beta_hat))

'Calculate R-square'
R_square = 1 - residuals.transpose()@residuals/(T*np.var(Y))
adj_R_square = 1-(1-R_square)*(T-1)/(T-N)

'Test Each Coefficient: beta_i'
't-test stat: N x 1'
t_stat = beta_hat.transpose()/var_beta_hat
' t-test significance level: N x 1'
p_val_t = 1-ss.norm.cdf(t_stat)

'Test of Joint Significance of Model'
F_stat = beta_hat.transpose()@varcov_beta_hat@beta_hat/\
         (residuals.transpose()@residuals)
'size: (1 x N)*(N x N)*(N x 1)/((1 x T) * (T x 1)) = 1 x 1'

p_val_F = 1-ss.chi2.cdf(F_stat,T-N)

REPORT = np.column_stack([beta_hat, t_stat,p_val_t])
print('Regression Statistics')
print('------------------------\n')
print(' REGRESSION STATISTICS  \n') 
print('------------------------\n')
print('beta             t_stat            p_val\n')
print(REPORT)
print('\n Joint significance of all coefficients\n',[F_stat,p_val_F])
print('R-Square is       \n',R_square)
print('Adjusted R Square \n',adj_R_square)
print('Standard Error    \n',sig)
print('Observations      \n',T) 
print('-------------------------\n')

Regression Statistics
------------------------

 REGRESSION STATISTICS  

------------------------

beta             t_stat            p_val

[[ 4.36852894e-04  4.23107957e-02  4.83125470e-01]
 [ 1.18510328e-02  9.92110150e-01  1.60571898e-01]
 [-8.03765435e-03 -3.63759339e-01  6.41981136e-01]
 [-2.94750783e-03 -9.72939856e-02  5.38753534e-01]
 [-1.04684586e-02 -2.57247902e-01  6.01506296e-01]]

 Joint significance of all coefficients
 [3.8987340730498786e-09, 1.0]
R-Square is       
 0.7064167623372359
Adjusted R Square 
 0.7040539193781795
Standard Error    
 0.010289870310637314
Observations      
 502
-------------------------



### XGBoost

In [42]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error

In [87]:
X,y = a_imp_features, Y

In [44]:
data_dmatrix = xgb.DMatrix(data=X,label=y)

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123, shuffle= False)

In [46]:
xg_reg = xgb.XGBRegressor(objective ='reg:squarederror', colsample_bytree = 0.3, learning_rate = 0.001,
                max_depth = 5, alpha = 10, n_estimators = 10)

In [47]:
xg_reg.fit(X_train,y_train)

preds = xg_reg.predict(X_test)

In [48]:
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE: %f" % (rmse))

RMSE: 0.494185


### Hyperparameter optimization

In [49]:
from sklearn.model_selection import train_test_split, GridSearchCV, TimeSeriesSplit

In [51]:
tscv = TimeSeriesSplit(n_splits=3)

In [88]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size= 7 * len(X) // 10,shuffle=False)

In [76]:
def _train_xgb(X_train, y_train, X_test, y_test):
    xg_reg = xgb.XGBRegressor()
    
    # Dictionary of all values we want to test for n_estimators
    params_xgb = {'learning_rate': [0.001, 0.01, 0.1, 1.0]}
    # Use gridsearch to test all values for all n estimators
    xgb_gs = GridSearchCV(xg_reg, params_xgb , cv=tscv, verbose=5)
    # Fit model to training data
    xgb_gs.fit(X_train, y_train)
    
    # Save best model
    xgb_best = xgb_gs.best_estimator_
    print(xgb_best) 
    # Check best n_neigbors value
#     print(xgb_best.best_params_)
    
    prediction = xgb_best.predict(X_test)

#     print(classification_report(y_test, prediction))
#     print(confusion_matrix(y_test, prediction))
    
    return xgb_best
xgb_model = _train_xgb(X_train, y_train, X_test, y_test) 

Fitting 3 folds for each of 4 candidates, totalling 12 fits
[CV 1/3] END ............................learning_rate=0.001; total time=   0.0s
[CV 2/3] END ............................learning_rate=0.001; total time=   0.0s
[CV 3/3] END ............................learning_rate=0.001; total time=   0.0s
[CV 1/3] END .............................learning_rate=0.01; total time=   0.0s
[CV 2/3] END .............................learning_rate=0.01; total time=   0.0s
[CV 3/3] END .............................learning_rate=0.01; total time=   0.0s
[CV 1/3] END ..............................learning_rate=0.1; total time=   0.0s
[CV 2/3] END ..............................learning_rate=0.1; total time=   0.0s
[CV 3/3] END ..............................learning_rate=0.1; total time=   0.0s
[CV 1/3] END ..............................learning_rate=1.0; total time=   0.0s
[CV 2/3] END ..............................learning_rate=1.0; total time=   0.0s
[CV 3/3] END ..............................learni

In [56]:
xgb_best

NameError: name 'xgb_best' is not defined

In [59]:
import numpy as np
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [60]:
reg = make_pipeline(StandardScaler(),SGDRegressor(max_iter=1000, tol=1e-3))

In [61]:
reg.fit(X, y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('sgdregressor', SGDRegressor())])

In [63]:
reg.get_params(deep=True)

{'memory': None,
 'steps': [('standardscaler', StandardScaler()),
  ('sgdregressor', SGDRegressor())],
 'verbose': False,
 'standardscaler': StandardScaler(),
 'sgdregressor': SGDRegressor(),
 'standardscaler__copy': True,
 'standardscaler__with_mean': True,
 'standardscaler__with_std': True,
 'sgdregressor__alpha': 0.0001,
 'sgdregressor__average': False,
 'sgdregressor__early_stopping': False,
 'sgdregressor__epsilon': 0.1,
 'sgdregressor__eta0': 0.01,
 'sgdregressor__fit_intercept': True,
 'sgdregressor__l1_ratio': 0.15,
 'sgdregressor__learning_rate': 'invscaling',
 'sgdregressor__loss': 'squared_loss',
 'sgdregressor__max_iter': 1000,
 'sgdregressor__n_iter_no_change': 5,
 'sgdregressor__penalty': 'l2',
 'sgdregressor__power_t': 0.25,
 'sgdregressor__random_state': None,
 'sgdregressor__shuffle': True,
 'sgdregressor__tol': 0.001,
 'sgdregressor__validation_fraction': 0.1,
 'sgdregressor__verbose': 0,
 'sgdregressor__warm_start': False}

In [79]:
from sklearn.metrics import mean_squared_error
def _train_sgd(X_train, y_train, X_test, y_test):
    sgd_reg = SGDRegressor()
    
    # Dictionary of all values we want to test for n_estimators
    params_sgd = {'learning_rate': ['optimal'],
                 'loss': ['squared_loss', 'huber', 'squared_epsilon_insensitive'],
                  'penalty': ['l2', 'l1', 'elasticnet']}
    # Use gridsearch to test all values for all n estimators
    sgd_gs = GridSearchCV(sgd_reg, params_sgd , cv=tscv, verbose=5)
    # Fit model to training data
    sgd_gs.fit(X_train, y_train)
    
    # Save best model
    sgd_best = sgd_gs.best_estimator_
    print(sgd_best) 
    # Check best n_neigbors value
#     print(sgd_best.best_params_)
    
    prediction = sgd_best.predict(X_test)
    rms = mean_squared_error(y_test, prediction, squared=False)
    mape = np.mean(np.abs((y_test - prediction) / y_test)) * 100
#     r2 = sgd_bestscore(X, y, sample_weight=None)
    print(sgd_best.score())
    print(mape)
    print(rms)
#     print(classification_report(y_test, prediction))
#     print(confusion_matrix(y_test, prediction))
    print()
    return sgd_best
sgd_model = _train_sgd(X_train, y_train, X_test, y_test) 

Fitting 3 folds for each of 9 candidates, totalling 27 fits
[CV 1/3] END learning_rate=optimal, loss=squared_loss, penalty=l2; total time=   0.0s
[CV 2/3] END learning_rate=optimal, loss=squared_loss, penalty=l2; total time=   0.0s
[CV 3/3] END learning_rate=optimal, loss=squared_loss, penalty=l2; total time=   0.0s
[CV 1/3] END learning_rate=optimal, loss=squared_loss, penalty=l1; total time=   0.0s
[CV 2/3] END learning_rate=optimal, loss=squared_loss, penalty=l1; total time=   0.0s
[CV 3/3] END learning_rate=optimal, loss=squared_loss, penalty=l1; total time=   0.0s
[CV 1/3] END learning_rate=optimal, loss=squared_loss, penalty=elasticnet; total time=   0.0s
[CV 2/3] END learning_rate=optimal, loss=squared_loss, penalty=elasticnet; total time=   0.0s
[CV 3/3] END learning_rate=optimal, loss=squared_loss, penalty=elasticnet; total time=   0.0s
[CV 1/3] END ..learning_rate=optimal, loss=huber, penalty=l2; total time=   0.0s
[CV 2/3] END ..learning_rate=optimal, loss=huber, penalty=l2;

TypeError: score() missing 2 required positional arguments: 'X' and 'y'

In [85]:
# score(X, y, sample_weight=None)

In [80]:
#TEST

In [92]:
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
def _train_sgd(X_train, y_train, X_test, y_test):
    
    scaler = StandardScaler()
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    sgd_reg = SGDRegressor()
    
    # Dictionary of all values we want to test for n_estimators
    params_sgd = {
    'alpha': 10.0 ** -np.arange(1, 7),
    'loss': ['squared_loss', 'huber', 'epsilon_insensitive'],
    'penalty': ['l2', 'l1', 'elasticnet'],
    'learning_rate': ['constant', 'optimal', 'invscaling']}
    # Use gridsearch to test all values for all n estimators
    sgd_gs = GridSearchCV(sgd_reg, params_sgd , cv=tscv, verbose=5)
    # Fit model to training data
    sgd_gs.fit(X_train, y_train)
    
    # Save best model
    sgd_best = sgd_gs.best_estimator_
    print(sgd_best) 
    print("Best score: " + str(sgd_gs.best_score_))
    # Check best n_neigbors value
#     print(sgd_best.best_params_)
    
    prediction = sgd_best.predict(X_test)
    rms = mean_squared_error(y_test, prediction, squared=False)
    mape = np.mean(np.abs((y_test - prediction) / y_test)) * 100
#     r2 = sgd_bestscore(X, y, sample_weight=None)
#     print(sgd_best.score())
    print(mape)
    print(rms)
#     print(classification_report(y_test, prediction))
#     print(confusion_matrix(y_test, prediction))
    print()
    return sgd_best
sgd_model = _train_sgd(X_train, y_train, X_test, y_test) 

Fitting 3 folds for each of 162 candidates, totalling 486 fits
[CV 1/3] END alpha=0.1, learning_rate=constant, loss=squared_loss, penalty=l2; total time=   0.0s
[CV 2/3] END alpha=0.1, learning_rate=constant, loss=squared_loss, penalty=l2; total time=   0.0s
[CV 3/3] END alpha=0.1, learning_rate=constant, loss=squared_loss, penalty=l2; total time=   0.0s
[CV 1/3] END alpha=0.1, learning_rate=constant, loss=squared_loss, penalty=l1; total time=   0.0s
[CV 2/3] END alpha=0.1, learning_rate=constant, loss=squared_loss, penalty=l1; total time=   0.0s
[CV 3/3] END alpha=0.1, learning_rate=constant, loss=squared_loss, penalty=l1; total time=   0.0s
[CV 1/3] END alpha=0.1, learning_rate=constant, loss=squared_loss, penalty=elasticnet; total time=   0.0s
[CV 2/3] END alpha=0.1, learning_rate=constant, loss=squared_loss, penalty=elasticnet; total time=   0.0s
[CV 3/3] END alpha=0.1, learning_rate=constant, loss=squared_loss, penalty=elasticnet; total time=   0.0s
[CV 1/3] END alpha=0.1, learnin

[CV 3/3] END alpha=0.01, learning_rate=invscaling, loss=squared_loss, penalty=elasticnet; total time=   0.0s
[CV 1/3] END alpha=0.01, learning_rate=invscaling, loss=huber, penalty=l2; total time=   0.0s
[CV 2/3] END alpha=0.01, learning_rate=invscaling, loss=huber, penalty=l2; total time=   0.0s
[CV 3/3] END alpha=0.01, learning_rate=invscaling, loss=huber, penalty=l2; total time=   0.0s
[CV 1/3] END alpha=0.01, learning_rate=invscaling, loss=huber, penalty=l1; total time=   0.0s
[CV 2/3] END alpha=0.01, learning_rate=invscaling, loss=huber, penalty=l1; total time=   0.0s
[CV 3/3] END alpha=0.01, learning_rate=invscaling, loss=huber, penalty=l1; total time=   0.0s
[CV 1/3] END alpha=0.01, learning_rate=invscaling, loss=huber, penalty=elasticnet; total time=   0.0s
[CV 2/3] END alpha=0.01, learning_rate=invscaling, loss=huber, penalty=elasticnet; total time=   0.0s
[CV 3/3] END alpha=0.01, learning_rate=invscaling, loss=huber, penalty=elasticnet; total time=   0.0s
[CV 1/3] END alpha=0.

[CV 2/3] END alpha=0.0001, learning_rate=optimal, loss=epsilon_insensitive, penalty=l2; total time=   0.0s
[CV 3/3] END alpha=0.0001, learning_rate=optimal, loss=epsilon_insensitive, penalty=l2; total time=   0.0s
[CV 1/3] END alpha=0.0001, learning_rate=optimal, loss=epsilon_insensitive, penalty=l1; total time=   0.0s
[CV 2/3] END alpha=0.0001, learning_rate=optimal, loss=epsilon_insensitive, penalty=l1; total time=   0.0s
[CV 3/3] END alpha=0.0001, learning_rate=optimal, loss=epsilon_insensitive, penalty=l1; total time=   0.0s
[CV 1/3] END alpha=0.0001, learning_rate=optimal, loss=epsilon_insensitive, penalty=elasticnet; total time=   0.0s
[CV 2/3] END alpha=0.0001, learning_rate=optimal, loss=epsilon_insensitive, penalty=elasticnet; total time=   0.0s
[CV 3/3] END alpha=0.0001, learning_rate=optimal, loss=epsilon_insensitive, penalty=elasticnet; total time=   0.0s
[CV 1/3] END alpha=0.0001, learning_rate=invscaling, loss=squared_loss, penalty=l2; total time=   0.0s
[CV 2/3] END alph

[CV 1/3] END alpha=1e-06, learning_rate=optimal, loss=squared_loss, penalty=l2; total time=   0.0s
[CV 2/3] END alpha=1e-06, learning_rate=optimal, loss=squared_loss, penalty=l2; total time=   0.0s
[CV 3/3] END alpha=1e-06, learning_rate=optimal, loss=squared_loss, penalty=l2; total time=   0.0s
[CV 1/3] END alpha=1e-06, learning_rate=optimal, loss=squared_loss, penalty=l1; total time=   0.0s
[CV 2/3] END alpha=1e-06, learning_rate=optimal, loss=squared_loss, penalty=l1; total time=   0.0s
[CV 3/3] END alpha=1e-06, learning_rate=optimal, loss=squared_loss, penalty=l1; total time=   0.0s
[CV 1/3] END alpha=1e-06, learning_rate=optimal, loss=squared_loss, penalty=elasticnet; total time=   0.0s
[CV 2/3] END alpha=1e-06, learning_rate=optimal, loss=squared_loss, penalty=elasticnet; total time=   0.0s
[CV 3/3] END alpha=1e-06, learning_rate=optimal, loss=squared_loss, penalty=elasticnet; total time=   0.0s
[CV 1/3] END alpha=1e-06, learning_rate=optimal, loss=huber, penalty=l2; total time= 

### Ridge Regression

In [101]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge()
from sklearn.model_selection import GridSearchCV
params_Ridge = {'alpha': [1,0.1,0.01,0.001,0.0001,0] , "fit_intercept": [True, False], "solver": ['svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga']}
Ridge_GS = GridSearchCV(ridge_reg, param_grid=params_Ridge, n_jobs=-1)
Ridge_GS.fit(X_train, y_train)
Ridge_GS.best_params_

{'alpha': 1, 'fit_intercept': False, 'solver': 'lsqr'}

In [96]:
tscv = TimeSeriesSplit(n_splits=5)

In [97]:
Ridgeregression = Ridge(random_state=3, **Ridge_GS.best_params_)
from sklearn.model_selection import cross_val_score
all_accuracies = cross_val_score(estimator=Ridgeregression, X=X_train, y=y_train, cv=tscv, verbose = 5)
all_accuracies

[CV] END ................................ score: (test=0.594) total time=   0.0s
[CV] END ................................ score: (test=0.584) total time=   0.0s
[CV] END ................................ score: (test=0.811) total time=   0.0s
[CV] END ................................ score: (test=0.781) total time=   0.0s
[CV] END ................................ score: (test=0.478) total time=   0.0s


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished


array([0.59399591, 0.58446439, 0.81076475, 0.78101125, 0.47759903])

In [98]:
print(all_accuracies.mean())

0.6495670669845296


In [102]:
Ridge_GS.score(X_test,y_test)

0.558397020190914