In [5]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
plt.style.use("fivethirtyeight")
%matplotlib inline

# For reading stock data from yahoo
from pandas_datareader.data import DataReader

# For time stamps
from datetime import datetime

In [6]:
df = pd.read_csv("df.csv")

In [7]:
df

Date  Mkt-RF   SMB   HML     RF
0    20200102    0.86 -0.85 -0.36  0.006
1    20200103   -0.67  0.37  0.02  0.006
2    20200106    0.36 -0.06 -0.56  0.006
3    20200107   -0.19 -0.01 -0.21  0.006
4    20200108    0.47 -0.05 -0.63  0.006
..        ...     ...   ...   ...    ...
163  20200825    0.36  0.14 -0.61  0.000
164  20200826    1.00 -1.11 -1.74  0.000
165  20200827    0.18 -0.36  0.98  0.000
166  20200828    0.70  0.30 -0.22  0.000
167  20200831   -0.04 -0.44 -1.75  0.000

[168 rows x 5 columns]

In [8]:
df

Date  Mkt-RF   SMB   HML     RF
0    20200102    0.86 -0.85 -0.36  0.006
1    20200103   -0.67  0.37  0.02  0.006
2    20200106    0.36 -0.06 -0.56  0.006
3    20200107   -0.19 -0.01 -0.21  0.006
4    20200108    0.47 -0.05 -0.63  0.006
..        ...     ...   ...   ...    ...
163  20200825    0.36  0.14 -0.61  0.000
164  20200826    1.00 -1.11 -1.74  0.000
165  20200827    0.18 -0.36  0.98  0.000
166  20200828    0.70  0.30 -0.22  0.000
167  20200831   -0.04 -0.44 -1.75  0.000

[168 rows x 5 columns]

In [9]:
df.dtypes

Date        int64
Mkt-RF    float64
SMB       float64
HML       float64
RF        float64
dtype: object

In [10]:
ADBE = DataReader('ADBE',  'yahoo', datetime(2020,1,2), datetime(2020,8,31))

In [11]:
ADBE

High         Low        Open       Close   Volume  \
Date                                                                  
2020-01-02  334.480011  329.170013  330.000000  334.429993  1990100   
2020-01-03  332.980011  328.690002  329.170013  331.809998  1577600   
2020-01-06  333.910004  328.190002  328.290009  333.709991  1874700   
2020-01-07  334.790009  332.309998  334.149994  333.390015  2500800   
2020-01-08  339.230011  333.399994  333.809998  337.869995  2248500   
...                ...         ...         ...         ...      ...   
2020-08-25  484.649994  474.429993  476.670013  484.429993  3967400   
2020-08-26  533.700012  492.230011  496.950012  528.489990  7780300   
2020-08-27  523.320007  504.459991  519.010010  510.320007  3631800   
2020-08-28  518.799988  510.940002  512.330017  516.440002  1926300   
2020-08-31  516.729980  507.769989  513.859985  513.390015  2346700   

             Adj Close  
Date                    
2020-01-02  334.429993  
2020-01-03  331.809998  
2020-01-06  333.709991  
2020-01-07  333.390015  
2020-01-08  337.869995  
...                ...  
2020-08-25  484.429993  
2020-08-26  528.489990  
2020-08-27  510.320007  
2020-08-28  516.440002  
2020-08-31  513.390015  

[168 rows x 6 columns]

In [12]:
a = df[1:168]

In [13]:
# a

In [14]:
# Y = ADBE = DataReader('ADBE',  'yahoo', datetime(2020,1,2), datetime(2020,8,31))
# T = Y.shape[0];
# # SPY = DataReader('SPY',  'yahoo', datetime(2020,1,1), datetime(2020,8,31))
# # F = np.diff(np.log(SPY['Adj Close'].values))
# F = a["Mkt-RF"].values
# 'Add Constant to X'
# X = np.column_stack([np.ones((T,1)), F])
# N = X.shape[1]

In [45]:
# len(Y)

167

In [15]:
# df

In [ ]:
# import numpy as np
# import scipy.stats as ss
# import pandas as pd
# from pandas_datareader import DataReader
# from datetime import datetime

# MSFT = DataReader('MSFT',  'yahoo', datetime(2020,1,1), datetime(2020,8,31))
# Y = np.diff(np.log(MSFT['Adj Close'].values))
# T = Y.shape[0];
# SPY = DataReader('SPY',  'yahoo', datetime(2020,1,1), datetime(2020,8,31))
# F = np.diff(np.log(SPY['Adj Close'].values))
# 'Add Constant to X'
# X = np.column_stack([np.ones((T,1)), F])
# N = X.shape[1]

# 'REGRESSION STARTS:'       
# 'Linear Regression of Y: T x 1 on' 
# 'Regressors X: T x N'

# invXX = np.linalg.inv(X.transpose()@X)
# 'OLS estimator beta: N x 1'
# beta_hat = invXX@X.transpose()@Y
# 'Predictive value of Y_t using OLS'  
# y_hat = X@beta_hat;       
# 'Residuals from OLS: Y - X*beta'        
# residuals = Y - y_hat;            
# 'variance of Y_t or residuals'
# sigma2 = (1/T)*(residuals.transpose()@residuals)
# 'standard deviation of Y_t or residuals'
# sig = np.sqrt(sigma2) 
# 'variance-covariance matrix of beta_hat'
# 'N x N: on-diagnal variance(beta_j)'
# 'N x N: off-diagnal cov(beta_i, beta_j)'
# varcov_beta_hat = (sigma2)*invXX
# var_beta_hat = np.sqrt(T*np.diag(varcov_beta_hat))

# 'Calculate R-square'
# R_square = 1 - residuals.transpose()@residuals/(T*np.var(Y))
# adj_R_square = 1-(1-R_square)*(T-1)/(T-N)

# 'Test Each Coefficient: beta_i'
# 't-test stat: N x 1'
# t_stat = beta_hat.transpose()/var_beta_hat
# ' t-test significance level: N x 1'
# p_val_t = 1-ss.norm.cdf(t_stat)

# 'Test of Joint Significance of Model'
# F_stat = beta_hat.transpose()@varcov_beta_hat@beta_hat/\
#          (residuals.transpose()@residuals)
# 'size: (1 x N)*(N x N)*(N x 1)/((1 x T) * (T x 1)) = 1 x 1'

# p_val_F = 1-ss.chi2.cdf(F_stat,T-N)

# REPORT = np.column_stack([beta_hat, t_stat,p_val_t])
# print('Regression Statistics')
# print('------------------------\n')
# print(' REGRESSION STATISTICS  \n') 
# print('------------------------\n')
# print('beta             t_stat            p_val\n')
# print(REPORT)
# print('\n Joint significance of all coefficients\n',[F_stat,p_val_F])
# print('R-Square is       \n',R_square)
# print('Adjusted R Square \n',adj_R_square)
# print('Standard Error    \n',sig)
# print('Observations      \n',T) 
# print('-------------------------\n')

In [16]:
import numpy as np
import scipy.stats as ss
import pandas as pd

In [52]:
'REGRESSION STARTS:'       
'Linear Regression of Y: T x 1 on' 
'Regressors X: T x N'

invXX = np.linalg.inv(X.transpose()@X)
'OLS estimator beta: N x 1'
beta_hat = invXX@X.transpose()@Y
'Predictive value of Y_t using OLS'  
y_hat = X@beta_hat;       
'Residuals from OLS: Y - X*beta'        
residuals = Y - y_hat;            
'variance of Y_t or residuals'
sigma2 = (1/T)*(residuals.transpose()@residuals)
'standard deviation of Y_t or residuals'
sig = np.sqrt(sigma2) 
'variance-covariance matrix of beta_hat'
'N x N: on-diagnal variance(beta_j)'
'N x N: off-diagnal cov(beta_i, beta_j)'
varcov_beta_hat = (sigma2)*invXX
var_beta_hat = np.sqrt(T*np.diag(varcov_beta_hat))

'Calculate R-square'
R_square = 1 - residuals.transpose()@residuals/(T*np.var(Y))
adj_R_square = 1-(1-R_square)*(T-1)/(T-N)

'Test Each Coefficient: beta_i'
't-test stat: N x 1'
t_stat = beta_hat.transpose()/var_beta_hat
' t-test significance level: N x 1'
p_val_t = 1-ss.norm.cdf(t_stat)

'Test of Joint Significance of Model'
F_stat = beta_hat.transpose()@varcov_beta_hat@beta_hat/\
         (residuals.transpose()@residuals)
'size: (1 x N)*(N x N)*(N x 1)/((1 x T) * (T x 1)) = 1 x 1'

p_val_F = 1-ss.chi2.cdf(F_stat,T-N)

REPORT = np.column_stack([beta_hat, t_stat,p_val_t])
print('Regression Statistics')
print('------------------------\n')
print(' REGRESSION STATISTICS  \n') 
print('------------------------\n')
print('beta             t_stat            p_val\n')
print(REPORT)
print('\n Joint significance of all coefficients\n',[F_stat,p_val_F])
print('R-Square is       \n',R_square)
print('Adjusted R Square \n',adj_R_square)
print('Standard Error    \n',sig)
print('Observations      \n',T) 
print('-------------------------\n')

Regression Statistics
------------------------

 REGRESSION STATISTICS  

------------------------

beta             t_stat            p_val

[[-1.02735135e+02 -3.89263665e-02  5.15525452e-01]
 [ 5.08572218e-06  3.89262152e-02  4.84474608e-01]
 [ 1.25774882e-02  1.81448951e+00  3.48011981e-02]
 [ 2.10900512e-03  1.20202355e-01  4.52161426e-01]
 [-6.88660105e-03 -6.37571822e-01  7.38123778e-01]
 [ 5.04496745e-01  4.86174192e-02  4.80612094e-01]]

 Joint significance of all coefficients
 [10235056481.322308, 0.0]
R-Square is       
 0.7687418413143047
Adjusted R Square 
 0.761559910920339
Standard Error    
 0.016048689850121183
Observations      
 167
-------------------------



In [53]:
Y = np.diff(np.log(ADBE['Adj Close'].values))
T = Y.shape[0];
# SPY = DataReader('SPY',  'yahoo', datetime(2020,1,1), datetime(2020,8,31))
# F = np.diff(np.log(SPY['Adj Close'].values))
F = a.values
'Add Constant to X'
X = np.column_stack([np.ones((T,1)), F])
N = X.shape[1]

'REGRESSION STARTS:'       
'Linear Regression of Y: T x 1 on' 
'Regressors X: T x N'

invXX = np.linalg.inv(X.transpose()@X)
'OLS estimator beta: N x 1'
beta_hat = invXX@X.transpose()@Y
'Predictive value of Y_t using OLS'  
y_hat = X@beta_hat;       
'Residuals from OLS: Y - X*beta'        
residuals = Y - y_hat;            
'variance of Y_t or residuals'
sigma2 = (1/T)*(residuals.transpose()@residuals)
'standard deviation of Y_t or residuals'
sig = np.sqrt(sigma2) 
'variance-covariance matrix of beta_hat'
'N x N: on-diagnal variance(beta_j)'
'N x N: off-diagnal cov(beta_i, beta_j)'
varcov_beta_hat = (sigma2)*invXX
var_beta_hat = np.sqrt(T*np.diag(varcov_beta_hat))

'Calculate R-square'
R_square = 1 - residuals.transpose()@residuals/(T*np.var(Y))
adj_R_square = 1-(1-R_square)*(T-1)/(T-N)

'Test Each Coefficient: beta_i'
't-test stat: N x 1'
t_stat = beta_hat.transpose()/var_beta_hat
' t-test significance level: N x 1'
p_val_t = 1-ss.norm.cdf(t_stat)

'Test of Joint Significance of Model'
F_stat = beta_hat.transpose()@varcov_beta_hat@beta_hat/\
         (residuals.transpose()@residuals)
'size: (1 x N)*(N x N)*(N x 1)/((1 x T) * (T x 1)) = 1 x 1'

p_val_F = 1-ss.chi2.cdf(F_stat,T-N)

REPORT = np.column_stack([beta_hat, t_stat,p_val_t])
print('Regression Statistics')
print('------------------------\n')
print(' REGRESSION STATISTICS  \n') 
print('------------------------\n')
print('beta             t_stat            p_val\n')
print(REPORT)
print('\n Joint significance of all coefficients\n',[F_stat,p_val_F])
print('R-Square is       \n',R_square)
print('Adjusted R Square \n',adj_R_square)
print('Standard Error    \n',sig)
print('Observations      \n',T) 
print('-------------------------\n')

Regression Statistics
------------------------

 REGRESSION STATISTICS  

------------------------

beta             t_stat            p_val

[[-1.02735135e+02 -3.89263665e-02  5.15525452e-01]
 [ 5.08572218e-06  3.89262152e-02  4.84474608e-01]
 [ 1.25774882e-02  1.81448951e+00  3.48011981e-02]
 [ 2.10900512e-03  1.20202355e-01  4.52161426e-01]
 [-6.88660105e-03 -6.37571822e-01  7.38123778e-01]
 [ 5.04496745e-01  4.86174192e-02  4.80612094e-01]]

 Joint significance of all coefficients
 [10235056481.322308, 0.0]
R-Square is       
 0.7687418413143047
Adjusted R Square 
 0.761559910920339
Standard Error    
 0.016048689850121183
Observations      
 167
-------------------------



In [ ]:
import ta

In [ ]:
aapl = ta.add_all_ta_features(ADBE, open="Open", high="High", low="Low", close="Close", volume="Volume")

In [ ]:
aapl

In [ ]:
aapl.columns

In [54]:
a

Date  Mkt-RF   SMB   HML     RF
1    20200103   -0.67  0.37  0.02  0.006
2    20200106    0.36 -0.06 -0.56  0.006
3    20200107   -0.19 -0.01 -0.21  0.006
4    20200108    0.47 -0.05 -0.63  0.006
5    20200109    0.65 -0.63 -0.48  0.006
..        ...     ...   ...   ...    ...
163  20200825    0.36  0.14 -0.61  0.000
164  20200826    1.00 -1.11 -1.74  0.000
165  20200827    0.18 -0.36  0.98  0.000
166  20200828    0.70  0.30 -0.22  0.000
167  20200831   -0.04 -0.44 -1.75  0.000

[167 rows x 5 columns]

In [56]:
a.columns

Index(['Date', 'Mkt-RF', 'SMB', 'HML', 'RF'], dtype='object')

In [65]:
import statsmodels.api as sm

## Forward Selection

We begin with the null model—a model that contains an intercept but no predictors.</br>
We then fit p simple linear regressions and add to the null model the variable that results in the
lowest RSS. </br>
We then add to that model the variable that results
in the lowest RSS for the new two-variable model.</br>
This approach is continued until some stopping rule is satisfied.

In [66]:
def forward_selection(data, target, significance_level=0.05):
    initial_features = data.columns.tolist()
    best_features = []
    while (len(initial_features)>0):
        remaining_features = list(set(initial_features)-set(best_features))
        new_pval = pd.Series(index=remaining_features)
        for new_column in remaining_features:
            model = sm.OLS(target, sm.add_constant(data[best_features+[new_column]])).fit()
            new_pval[new_column] = model.pvalues[new_column]
        min_p_value = new_pval.min()
        if(min_p_value<significance_level):
            best_features.append(new_pval.idxmin())
        else:
            break
    return best_features

In [74]:
X = a[['Mkt-RF', 'SMB', 'HML', 'RF']]
X.shape

(167, 4)

In [93]:
Y = np.diff(np.log(ADBE['Adj Close'].values))

In [94]:
Y.shape

(167,)

In [97]:
new_y= Y.reshape(-1,1)

In [98]:
new_y.shape

(167, 1)

In [100]:
forward_selection(X,new_y )

c:\users\adhar\anaconda3\envs\fintech\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  
c:\users\adhar\anaconda3\envs\fintech\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  
c:\users\adhar\anaconda3\envs\fintech\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


['Mkt-RF', 'HML']

## Backward Selection

We start with all variables in the model, and backward remove the variable with the largest p-value—that is, the variable
that is the least statistically significant. The new (p − 1)-variable
model is fit, and the variable with the largest p-value is removed. This
procedure continues until a stopping rule is reached. For instance, we
may stop when all remaining variables have a p-value below some
threshold.

In [102]:
def backward_elimination(data, target,significance_level = 0.05):
    features = data.columns.tolist()
    while(len(features)>0):
        features_with_constant = sm.add_constant(data[features])
        p_values = sm.OLS(target, features_with_constant).fit().pvalues[1:]
        max_p_value = p_values.max()
        if(max_p_value >= significance_level):
            excluded_feature = p_values.idxmax()
            features.remove(excluded_feature)
        else:
            break 
    return features

In [103]:
backward_elimination(X,new_y)

['Mkt-RF', 'HML']

## Mixed Selection

This is a combination of forward and backward selection. We start with no variables in the model, and as with forward selection
selection, we add the variable that provides the best fit. We continue
to add variables one-by-one. Hence, if at any point the
p-value for one of the variables in the model rises above a certain
threshold, then we remove that variable from the model. We continue
to perform these forward and backward steps until all variables
in the model have a sufficiently low p-value, and all variables outside
the model would have a large p-value if added to the model.

In [104]:
def stepwise_selection(data, target,SL_in=0.05,SL_out = 0.05):
    initial_features = data.columns.tolist()
    best_features = []
    while (len(initial_features)>0):
        remaining_features = list(set(initial_features)-set(best_features))
        new_pval = pd.Series(index=remaining_features)
        for new_column in remaining_features:
            model = sm.OLS(target, sm.add_constant(data[best_features+[new_column]])).fit()
            new_pval[new_column] = model.pvalues[new_column]
        min_p_value = new_pval.min()
        if(min_p_value<SL_in):
            best_features.append(new_pval.idxmin())
            while(len(best_features)>0):
                best_features_with_constant = sm.add_constant(data[best_features])
                p_values = sm.OLS(target, best_features_with_constant).fit().pvalues[1:]
                max_p_value = p_values.max()
                if(max_p_value >= SL_out):
                    excluded_feature = p_values.idxmax()
                    best_features.remove(excluded_feature)
                else:
                    break 
        else:
            break
    return best_features

In [105]:
stepwise_selection(X,new_y)

c:\users\adhar\anaconda3\envs\fintech\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  
c:\users\adhar\anaconda3\envs\fintech\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  
c:\users\adhar\anaconda3\envs\fintech\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


['Mkt-RF', 'HML']

## Implementation on Important Features

In [17]:
a

Date  Mkt-RF   SMB   HML     RF
1    20200103   -0.67  0.37  0.02  0.006
2    20200106    0.36 -0.06 -0.56  0.006
3    20200107   -0.19 -0.01 -0.21  0.006
4    20200108    0.47 -0.05 -0.63  0.006
5    20200109    0.65 -0.63 -0.48  0.006
..        ...     ...   ...   ...    ...
163  20200825    0.36  0.14 -0.61  0.000
164  20200826    1.00 -1.11 -1.74  0.000
165  20200827    0.18 -0.36  0.98  0.000
166  20200828    0.70  0.30 -0.22  0.000
167  20200831   -0.04 -0.44 -1.75  0.000

[167 rows x 5 columns]

In [18]:
a_imp_features = a[['Mkt-RF', 'HML']]

In [19]:
Y = np.diff(np.log(ADBE['Adj Close'].values))
T = Y.shape[0];
# SPY = DataReader('SPY',  'yahoo', datetime(2020,1,1), datetime(2020,8,31))
# F = np.diff(np.log(SPY['Adj Close'].values))
F = a_imp_features.values
'Add Constant to X'
X = np.column_stack([np.ones((T,1)), F])
N = X.shape[1]

'REGRESSION STARTS:'       
'Linear Regression of Y: T x 1 on' 
'Regressors X: T x N'

invXX = np.linalg.inv(X.transpose()@X)
'OLS estimator beta: N x 1'
beta_hat = invXX@X.transpose()@Y
'Predictive value of Y_t using OLS'  
y_hat = X@beta_hat;       
'Residuals from OLS: Y - X*beta'        
residuals = Y - y_hat;            
'variance of Y_t or residuals'
sigma2 = (1/T)*(residuals.transpose()@residuals)
'standard deviation of Y_t or residuals'
sig = np.sqrt(sigma2) 
'variance-covariance matrix of beta_hat'
'N x N: on-diagnal variance(beta_j)'
'N x N: off-diagnal cov(beta_i, beta_j)'
varcov_beta_hat = (sigma2)*invXX
var_beta_hat = np.sqrt(T*np.diag(varcov_beta_hat))

'Calculate R-square'
R_square = 1 - residuals.transpose()@residuals/(T*np.var(Y))
adj_R_square = 1-(1-R_square)*(T-1)/(T-N)

'Test Each Coefficient: beta_i'
't-test stat: N x 1'
t_stat = beta_hat.transpose()/var_beta_hat
' t-test significance level: N x 1'
p_val_t = 1-ss.norm.cdf(t_stat)

'Test of Joint Significance of Model'
F_stat = beta_hat.transpose()@varcov_beta_hat@beta_hat/\
         (residuals.transpose()@residuals)
'size: (1 x N)*(N x N)*(N x 1)/((1 x T) * (T x 1)) = 1 x 1'

p_val_F = 1-ss.chi2.cdf(F_stat,T-N)

REPORT = np.column_stack([beta_hat, t_stat,p_val_t])
print('Regression Statistics')
print('------------------------\n')
print(' REGRESSION STATISTICS  \n') 
print('------------------------\n')
print('beta             t_stat            p_val\n')
print(REPORT)
print('\n Joint significance of all coefficients\n',[F_stat,p_val_F])
print('R-Square is       \n',R_square)
print('Adjusted R Square \n',adj_R_square)
print('Standard Error    \n',sig)
print('Observations      \n',T) 
print('-------------------------\n')

Regression Statistics
------------------------

 REGRESSION STATISTICS  

------------------------

beta             t_stat            p_val

[[ 3.18421997e-05  1.94475120e-03  4.99224157e-01]
 [ 1.25114462e-02  1.80272289e+00  3.57158724e-02]
 [-6.52896695e-03 -6.26781229e-01  7.34598675e-01]]

 Joint significance of all coefficients
 [2.2942814912755285e-09, 1.0]
R-Square is       
 0.7650587144161312
Adjusted R Square 
 0.7621935767870596
Standard Error    
 0.016175984528913584
Observations      
 167
-------------------------



## Implementing on Mkt-RF

In [21]:
a_mktrf = a[['Mkt-RF']]

In [22]:
Y = np.diff(np.log(ADBE['Adj Close'].values))
T = Y.shape[0];
# SPY = DataReader('SPY',  'yahoo', datetime(2020,1,1), datetime(2020,8,31))
# F = np.diff(np.log(SPY['Adj Close'].values))
F = a_mktrf.values
'Add Constant to X'
X = np.column_stack([np.ones((T,1)), F])
N = X.shape[1]

'REGRESSION STARTS:'       
'Linear Regression of Y: T x 1 on' 
'Regressors X: T x N'

invXX = np.linalg.inv(X.transpose()@X)
'OLS estimator beta: N x 1'
beta_hat = invXX@X.transpose()@Y
'Predictive value of Y_t using OLS'  
y_hat = X@beta_hat;       
'Residuals from OLS: Y - X*beta'        
residuals = Y - y_hat;            
'variance of Y_t or residuals'
sigma2 = (1/T)*(residuals.transpose()@residuals)
'standard deviation of Y_t or residuals'
sig = np.sqrt(sigma2) 
'variance-covariance matrix of beta_hat'
'N x N: on-diagnal variance(beta_j)'
'N x N: off-diagnal cov(beta_i, beta_j)'
varcov_beta_hat = (sigma2)*invXX
var_beta_hat = np.sqrt(T*np.diag(varcov_beta_hat))

'Calculate R-square'
R_square = 1 - residuals.transpose()@residuals/(T*np.var(Y))
adj_R_square = 1-(1-R_square)*(T-1)/(T-N)

'Test Each Coefficient: beta_i'
't-test stat: N x 1'
t_stat = beta_hat.transpose()/var_beta_hat
' t-test significance level: N x 1'
p_val_t = 1-ss.norm.cdf(t_stat)

'Test of Joint Significance of Model'
F_stat = beta_hat.transpose()@varcov_beta_hat@beta_hat/\
         (residuals.transpose()@residuals)
'size: (1 x N)*(N x N)*(N x 1)/((1 x T) * (T x 1)) = 1 x 1'

p_val_F = 1-ss.chi2.cdf(F_stat,T-N)

REPORT = np.column_stack([beta_hat, t_stat,p_val_t])
print('Regression Statistics')
print('------------------------\n')
print(' REGRESSION STATISTICS  \n') 
print('------------------------\n')
print('beta             t_stat            p_val\n')
print(REPORT)
print('\n Joint significance of all coefficients\n',[F_stat,p_val_F])
print('R-Square is       \n',R_square)
print('Adjusted R Square \n',adj_R_square)
print('Standard Error    \n',sig)
print('Observations      \n',T) 
print('-------------------------\n')

Regression Statistics
------------------------

 REGRESSION STATISTICS  

------------------------

beta             t_stat            p_val

[[0.00157793 0.08259999 0.46708481]
 [0.01081878 1.43383045 0.07581033]]

 Joint significance of all coefficients
 [7.2751643925977e-10, 1.0]
R-Square is       
 0.6727609240417646
Adjusted R Square 
 0.670777656914745
Standard Error    
 0.019090778169943815
Observations      
 167
-------------------------



## Implementing on HML

In [23]:
a_hml = a[['HML']]

In [24]:
Y = np.diff(np.log(ADBE['Adj Close'].values))
T = Y.shape[0];
# SPY = DataReader('SPY',  'yahoo', datetime(2020,1,1), datetime(2020,8,31))
# F = np.diff(np.log(SPY['Adj Close'].values))
F = a_hml.values
'Add Constant to X'
X = np.column_stack([np.ones((T,1)), F])
N = X.shape[1]

'REGRESSION STARTS:'       
'Linear Regression of Y: T x 1 on' 
'Regressors X: T x N'

invXX = np.linalg.inv(X.transpose()@X)
'OLS estimator beta: N x 1'
beta_hat = invXX@X.transpose()@Y
'Predictive value of Y_t using OLS'  
y_hat = X@beta_hat;       
'Residuals from OLS: Y - X*beta'        
residuals = Y - y_hat;            
'variance of Y_t or residuals'
sigma2 = (1/T)*(residuals.transpose()@residuals)
'standard deviation of Y_t or residuals'
sig = np.sqrt(sigma2) 
'variance-covariance matrix of beta_hat'
'N x N: on-diagnal variance(beta_j)'
'N x N: off-diagnal cov(beta_i, beta_j)'
varcov_beta_hat = (sigma2)*invXX
var_beta_hat = np.sqrt(T*np.diag(varcov_beta_hat))

'Calculate R-square'
R_square = 1 - residuals.transpose()@residuals/(T*np.var(Y))
adj_R_square = 1-(1-R_square)*(T-1)/(T-N)

'Test Each Coefficient: beta_i'
't-test stat: N x 1'
t_stat = beta_hat.transpose()/var_beta_hat
' t-test significance level: N x 1'
p_val_t = 1-ss.norm.cdf(t_stat)

'Test of Joint Significance of Model'
F_stat = beta_hat.transpose()@varcov_beta_hat@beta_hat/\
         (residuals.transpose()@residuals)
'size: (1 x N)*(N x N)*(N x 1)/((1 x T) * (T x 1)) = 1 x 1'

p_val_F = 1-ss.chi2.cdf(F_stat,T-N)

REPORT = np.column_stack([beta_hat, t_stat,p_val_t])
print('Regression Statistics')
print('------------------------\n')
print(' REGRESSION STATISTICS  \n') 
print('------------------------\n')
print('beta             t_stat            p_val\n')
print(REPORT)
print('\n Joint significance of all coefficients\n',[F_stat,p_val_F])
print('R-Square is       \n',R_square)
print('Adjusted R Square \n',adj_R_square)
print('Standard Error    \n',sig)
print('Observations      \n',T) 
print('-------------------------\n')

Regression Statistics
------------------------

 REGRESSION STATISTICS  

------------------------

beta             t_stat            p_val

[[0.00273231 0.08128889 0.46760611]
 [0.00077795 0.03932687 0.48431489]]

 Joint significance of all coefficients
 [2.910325477360346e-10, 1.0]
R-Square is       
 0.0015442143563745292
Adjusted R Square 
 -0.004507032829344393
Standard Error    
 0.03334690032388665
Observations      
 167
-------------------------

